### PR TITLE
feat: support absolute path

### PR DESCRIPTION
**Pull request by fuweid**
The github repo support relative path and the links starting with `/` will be
relative to the repository root. It's easy to link to files, such as
MAINTAINERS, LICENSE and so on.

This patch is to introduce `allow-absolute-patch` flag to allow absolute
path to join with `--root` and evaluate the file link.

REF:

* https://github.blog/2013-01-31-relative-links-in-markup-files/
* https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links

### CODE REVIEW

**Comment by fuweid** [comment]
ping @crawford ~

**Comment by crawford** [comment]
I don't like the idea of allowing absolute paths by default, but I think it's probably okay to put it behind a flag (e.g. `--allow-absolute-paths`). I'm not sure about using the working directory as the base either. Does it make more sense to use the specified (`--root`) instead?

**Comment by fuweid** [comment]
Hi @crawford Thanks for the comment. Agree with you about that we should not use current dir as root because it might be conflict with `--root`. The `--root` should be root path and use toggle to evaluate any absolute paths.

I add `--allow-absolute-paths` as flag to allow checker to join the path with `--root` and evaluate it.

Please take a look. Thanks!

**Comment by fuweid** [comment]
Thanks! @crawford

**Comment by crawford** [comment]
Let me do a little cleanup on my end and then I'll cut a new release for you.

**Pull request merged**
